import mongoose from "mongoose"

export interface ILiveInternship {
  _id: string
  company: string
  role: string
  domain: string
  location: string
  workMode: "Remote" | "In-Person" | "Hybrid" | "Unknown"
  stipendNote: string | null
  stipendMin: number | null
  stipendMax: number | null
  applyUrl: string
  source: string // "Internshala", "LinkedIn", "Unstop", etc.
  trustScore: number | null // Generated by AI if checked
  AI_Summary: string | null // One line what this is
  fetchedAt: Date
  expiresAt: Date // Auto delete after some time
}

const LiveInternshipSchema = new mongoose.Schema(
  {
    company: { type: String, required: true },
    role: { type: String, required: true },
    domain: { type: String, required: true, index: true },
    location: { type: String, required: true },
    workMode: {
      type: String,
      enum: ["Remote", "In-Person", "Hybrid", "Unknown"],
      default: "Unknown",
    },
    stipendNote: { type: String, default: null },
    stipendMin: { type: Number, default: null, index: true },
    stipendMax: { type: Number, default: null },
    applyUrl: { type: String, required: true },
    source: { type: String, required: true }, // Platform scraped from
    trustScore: { type: Number, default: null },
    AI_Summary: { type: String, default: null },
    fetchedAt: { type: Date, default: Date.now },
    expiresAt: { type: Date, expires: 0 }, // TTL index
  },
  { timestamps: true }
)

// Ensure we don't have duplicates for the same role at the same company
LiveInternshipSchema.index({ company: 1, role: 1 }, { unique: true })

export const LiveInternship =
  mongoose.models.LiveInternship ||
  mongoose.model<ILiveInternship>("LiveInternship", LiveInternshipSchema)
